version: '2'
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    # ports:
    #   - 3000:3000
    # command: node index.js
    command: npm run dev